---
platform: linux


inputs:
- name: git-repo
- name: metadata

run:
  path: bash
  args:
  - -exc
  - |  
    set +x
    cfpass=$(printenv cf_deploy_password)
    cfuser=$(printenv cf_deploy_user)
    build_id=$(cat metadata/build_id)

    cf login -u $cfuser -p $cfpass -a https://api.system-$cf_env.gp2.axadmin.net -o $cf_organization -s $cf_space
    set -x

    greenApps=$(cf apps | grep $cf_app_name-green | { grep -v grep || true; })
    if [[ -z $greenApps ]]; then exit 0; fi

    cf map-route $cf_app_name-green apps-$cf_env.gp2.axadmin.net -n $cf_app_name

    cf unmap-route $cf_app_name apps-$cf_env.gp2.axadmin.net -n $cf_app_name

    cf unmap-route $cf_app_name-green apps-$cf_env.gp2.axadmin.net -n $cf_app_name-green

    cf stop $cf_app_name
    cf delete $cf_app_name -f
    # Remove the Green-Temp-Route.
    cf delete-route apps-$cf_env.gp2.axadmin.net --hostname $cf_app_name-green -f

    # Rename Green app to Blue app.
    cf rename $cf_app_name-green $cf_app_name
    curl -X POST -H 'Content-type: application/json' --data '{"title": "'${cf_space}' '${cf_app_name}' Blue-To-Green Switched","text": "[View Job Blue-To-Green Results](https://concourse-'${cf_env}'.gp2.axadmin.net/builds/'${build_id}')"}' ${teams_url}
