---
platform: linux
 
inputs:
- name: git-repo
outputs:
- name: deployables
run:
  path: sh
  args:
  - -exc
  - |
    fileprefix=$(printenv file_prefix)
    input_directory=${PWD}/git-repo
    output_directory=${PWD}/deployables
    manifest_file=${output_directory}/ci/pipelines/manifest.yml
    
    if [ "$cf_space" = "development" ]; then
      artifact=${input_directory}/artifact
      zip_file=${fileprefix}-*.zip 
      unzip ${input_directory}/${zip_file} -d ${output_directory}
    else
      mkdir -p ${output_directory}/ci/pipelines
      cp $input_directory/ci/pipelines/manifest.yml ${output_directory}/ci/pipelines/
    fi


    echo "Listing the directory"
    ls -a
    echo "Listing the directory-End"
    sed -i -e "s/\[buildpack_one\]/${buildpack_one}/" ${manifest_file}
    sed -i -e "s/\[buildpack_two\]/${buildpack_two}/" ${manifest_file}
    sed -i -e "s/\[app_name\]/${cf_app_name}-green/" ${manifest_file}
    sed -i -e "s/\[instances\]/${instance_number}/" ${manifest_file}
    sed -i -e "s/\[memory\]/${memory}/" ${manifest_file}
    sed -i -e "s/\[newrelic_app_name\]/${cf_app_name}/" ${manifest_file}
    sed -i -e "s/\[newrelic_app_lic\]/${newrelic_app_lic}/" ${manifest_file}
    sed -i -e "s/\[s3_access_key\]/${s3_access_key}/" ${manifest_file}
    sed -i -e "s/\[s3_bucket\]/${s3_bucket}/" ${manifest_file}
    sed -i -e "s/\[s3_secret_key\]/${s3_secret_key}/" ${manifest_file}
    sed -i -e "s~\[s3_url\]~${s3_url}~" ${manifest_file}
    sed -i -e "s/\[resilience_policy_min_wait_time_msecs\]~${resilience_policy_min_wait_time_msecs}/" ${manifest_file}
    sed -i -e "s/\[resilience_policy_max_wait_time_msecs\]~${resilience_policy_max_wait_time_msecs}/" ${manifest_file}
    sed -i -e "s/\[resilience_policy_max_retry_count\]~${resilience_policy_max_retry_count}/" ${manifest_file}